### PR TITLE
Additional logging on prime mismatches (fixes #102)

### LINKED ISSUE #102: Improve Visibility On StubMappings Mismatch
Currently, if you were to wrongly prime simulacron for a query you are returned an exhausted result set. There is no indication in the logs from simulacron that anything has went wrong or that no stubbing has been found. This can lead to an increased time for the developer to investigate, identify their mistake and rectify it (this has happened to me).

My initial thoughts on improving this would be to log a statement saying that no stub mapping was found for this query. From a quick look at the code, I can see that there are default responses for each of the message types. In this case, we may not want to have this log for all message types ie. (STARTUP/REGISTER) but it could be very useful for other types (QUERY/EXECUTE/PREPARE/BATCH).

### PR DESCRIPTION
**Pull request by michaelmcfadyen**
These are my initial thoughts on some additional logs that could be useful. Let me know your thoughts on the format and if there are any more we can add.

### CODE REVIEW

File: native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java [hunk 1]
```diff
@@ -412,6 +412,7 @@ void handle(ChannelHandlerContext ctx, Frame frame) {
       } else if (frame.message instanceof Query) {
         Query query = (Query) frame.message;
         String queryStr = query.query;
+        logger.warn("No stub mapping found for message type QUERY: \"{}\"", queryStr);
```
Comment (joao-r-reis) [inline native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:415]: We might want to avoid logging this message when a `USE _KEYSPACE_` request is executed. Note that right after this line there is some logic to handle these requests.

The driver typically sends those out when a user specifies the default keyspace so it could result in a lot of log messages that are not useful.

Comment (michaelmcfadyen) [reply native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java]: good point, will move it down to only log when the query is not a 'USE' query

File: native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java [hunk 2]
```diff
@@ -423,6 +423,7 @@ void handle(ChannelHandlerContext ctx, Frame frame) {
             response = new SetKeyspace(keyspace);
           }
         } else {
+          logger.warn("No stub mapping found for message type QUERY: \"{}\"", queryStr);
```
Comment (adutra) [inline native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:426]: How about adding a DEBUG-level message on line 365 to tell users that we did find a stub mapping? That could also be helpful when debugging Simulacron imo.

File: native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java [hunk 3]
```diff
@@ -431,13 +432,15 @@ void handle(ChannelHandlerContext ctx, Frame frame) {
...
         Execute execute = (Execute) frame.message;
+        logger.warn("No stub mapping found for message type EXECUTE: \"{}\"", execute.toString());
         String hex = new BigInteger(1, execute.queryId).toString(16);
         response = new Unprepared("No prepared statement with id: " + hex, execute.queryId);
       } else if (frame.message instanceof Prepare) {
         // fake up a prepared statement from the message and register an internal prime for it.
         Prepare prepare = (Prepare) frame.message;
         // TODO: Maybe attempt to identify bind parameters
         String query = prepare.cqlQuery;
+        logger.info("No stub mapping found for message type PREPARE: \"{}\". Registering priming...", query);
```
Comment (adutra) [inline native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:443]: Why info for this one?

File: native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java (hunk 2 above)
Comment (michaelmcfadyen) [reply native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:426]: yeah, good idea. Will add it in.

File: native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java (hunk 3 above)
Comment (michaelmcfadyen) [reply native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:443]: I would assume a mismatch on a prepared statement would occur much more often. Also, I would expect devs to not prime all prepared statements. That's why I was thinking of having a lower log level for this one. Thinking of it more, we could even lower it down to debug. 

What are your thoughts on this?

Comment (adutra) [reply native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:443]: OK, makes sense, let's go with with info.

File: native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java (hunk 2 above)
Comment (michaelmcfadyen) [reply native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java:427]: added new debug log line in latest commit
