### PR TITLE
Differentiate between the `then` affecting the prepared statement and the bound statement

### LINKED ISSUE #23: Timeout not working for priming prepare statement
After priming a prepare statement Frame, the driver ignores the delayInMs when the Prepare frame is executed.

### PR DESCRIPTION
**Pull request by bjmb**
When I wanted an exception to happen on the bound statement (I think this is what happens by default) it was happening on the prepared statement, this is changed by the first commit.

I'm not sure of the use of `ignore_on_prepare`, but I think it should be used to determine if the action should be on the prepared statement or on the bound statement. I'm not sure about this part so I've done in the second commit.

I can squash them if we want to merge both of them.

Fixes #23

### CODE REVIEW

**Comment by landim** [comment]
I think this is related with https://github.com/datastax/simulacron/pull/24 , wdyt?

**Comment by bjmb** [comment]
Yes, it looks related, I think the delay should work as expected now with this PR but I'll test it to be sure.

**Comment by bjmb** [comment]
This doesn't work for delaying because `ignore_on_prepare` is an attribute of `ErrorResult`, not of the more generic `Result`(which has the attribute `delay_in_ms`).
I have no strong feeling about using a `prepared_then` or moving `ignore_on_prepare` to `Result` and using `ignore_on_prepare`.
`ignore_on_prepare` might be used for something else I'm not aware of.

**Comment by landim** [comment]
You are right! 
btw, I am +1 on your PR.

File: common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java [hunk 1]
```diff
@@ -103,10 +103,12 @@ public Prepared toPrepared() {
...
     if (frame.message instanceof Prepare) {
       if (primedRequest.when instanceof Query) {
-        if (primedRequest.then instanceof SuccessResult
-            || (primedRequest.then instanceof ErrorResult
-                && ((ErrorResult) primedRequest.then).isignoreOnPrepare())) {
+        if (primedRequest.then instanceof SuccessResult) {
           return this.toPreparedAction();
+        } else if (primedRequest.then instanceof ErrorResult) {
+          if (((ErrorResult) primedRequest.then).isignoreOnPrepare()) {
+            return Collections.emptyList();
```
Comment (tolbertam) [inline common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: Question, in this case we won't return a response for `Prepare` messages at all right?    Shouldn't we still be returning a `PreparedResponse` in this case since we need it to in order for the BoundStatement to fail?

Comment (bjmb) [reply common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: In this particular case it will end up [here](https://github.com/datastax/simulacron/blob/46ace5bdcc1b541a358f0dbbd78ec77a8dc6fdcd/native-server/src/main/java/com/datastax/oss/simulacron/server/BoundNode.java#L407) and a response would be sent back.

Comment (tolbertam) [reply common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: ah ok cool got it, thanks!  Will take another quick look and merge if I don't find any problems.

Comment (bjmb) [reply common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: Before merging I'd decide if we want to reuse `ignore_on_prepare` or create a new field `prepared_then`. If we go with the first I'd move `ignore_on_prepare` to `Result` so we can solve https://github.com/datastax/simulacron/pull/24 as well. Sorry, I understand this PR is a bit confusing.

Comment (tolbertam) [reply common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: 👍 I like moving `ignore_on_prepare` to Result.  I'll make that change.

Comment (tolbertam) [reply common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: I'm almost done with that change,  was more code changes than I expected, but seems to be working good.  Will push this morning and merge.

Comment (bjmb) [reply common/src/main/java/com/datastax/oss/simulacron/common/stubbing/Prime.java]: Awesome, thanks for taking a look

**Comment by tolbertam** [comment]
@bjmb , pushed my changes, if you could give it a look and ensure my changes are ok I'll proceed with merging and doing a release, thanks!

**Comment by bjmb** [comment]
:+1: LGTM @tolbertam
